def space_constants():
    def set_attr(self, name, value):
        if hasattr(self, name):
            raise AttributeError(
                "Cannot reassign members"
            )
        self.__dict__[name] = value
    cls = type('SpaceConstants', (), {
        '__setattr__': set_attr
    })
    return cls()


sc = space_constants()

sc.DFE_TARGETS = "CAEScFfqlIEG6gUYogFWrAISK1WDAg+hAZoCDgIU1gYEOIACFkLMAeQBnASLATlASUuyAyqCAjY5igOMBQzfA/IClwFbApUC4ANbtgKVAS7OAX8YswHFBhgDwAOPAmGEBt4OfKkB5weSB5AFASkiN68akgMaxAMSAQEBA9kBO7UBFE1KVwIDBGs3go6BBgEBAgMECQgJAQIEAQMEAQMBBQEBBAUEFQYCBgUEAwMBDwIBAgOrARwBEwMEAg0mrwESfTEcAQEKG4EBMxghChMBDwYGASI3hAEODEwXCVh/EREZA4sBYwEdFAgIIwkQcGQRDzQ2fTC2AjfVAQIBAYoBGRg2FhYFBwEqNzACJShzFFblAo0CFxpFNBzaAd0DHjIRI4sBJZcBPdwBCQGhAUd2A7kBLBVPngEECHl0UEUMtQETigHMAgUFCc0BBUUlTywdHDgBiAJ+vgKhAU0uAcYCAWQ/5ALUAw1UwQHUBpIBCdQDhgL4AY4CBQICjARbGFBGWzA1CAEMOQH+BRAOCAZywAIDyQZ2MgM3BxsoAgUEBwcHFia3AgcGTBwHBYwBAlcBggFxSGgIrAEEBw4QEqUCASsWadsHCgUCBQMD7QICA3tXCUw7ugJZAwGyAUwpIwM5AwkDBQMJA5sBCw8BNxBVVBwVKhebARkBAwsQEAgEAhESAgQJEBCZATMdzgEBBwG8AQQYKSMUkAEDAwY/CTs4/wEaAUt1AwEDAQUBAgIEAwYEDx1dB2wGeBFgTQ"
sc.GOOGLE_PUBKEY = "AAAAgMom/1a/v0lblO2Ubrt60J2gcuXSljGFQXgcyZWveWLEwo6prwgi3iJIZdodyhKZQrNWp5nKJ3srRXcUW+F1BD3baEVGcmEgqaLZUNBjm057pKRI16kB0YppeGx5qIQ5QjKzsR8ETQbKLNWgRY0QRNVz34kMJR3P/LgHax/6rmf5AAAAAwEAAQ=="
sc.ACCOUNT = "HOSTED_OR_GOOGLE"

sc.ssl_verify = True
sc.BASE = "https://android.clients.google.com/"
sc.PLAYSTORE_BASE = "https://play-fe.googleapis.com/"
sc.PLAYSTORE_FDFE = sc.PLAYSTORE_BASE + "fdfe/"
sc.FDFE = sc.BASE + "fdfe/"
sc.AUTH_URL = sc.BASE + "auth"
sc.CHECKIN_URL = sc.BASE + "checkin"
sc.SEARCH_URL = sc.FDFE + "search"
sc.UPLOAD_URL = sc.FDFE + "uploadDeviceConfig"
sc.TOC_URL = sc.FDFE + "toc"
sc.ACCEPT_TOS_URL = sc.FDFE + "acceptTos"
sc.LEGACY_LIST_URL = sc.FDFE + "list"
sc.LIST_TEST_URL = sc.PLAYSTORE_FDFE + "listTopChartItems"
sc.LIST_TEST_V2_URL = sc.PLAYSTORE_FDFE + "browseTopCharts"
sc.CONTENT_TYPE_URLENC = "application/x-www-form-urlencoded; charset=UTF-8"
sc.CONTENT_TYPE_PROTO = "application/x-protobuf"

# https://play-fe.googleapis.com/fdfe/browseTopCharts?c=3&cat=GAME&scat=GAME&stcid=apps_topselling_paid&ups=true

ctr = space_constants()

ctr.APPS_TOP_SELLING_PAID = "apps_topselling_paid"
ctr.APPS_TOP_SELLING_FREE = "apps_topselling_free"
ctr.APPS_TOP_GROSSING = "apps_topgrossing"
ctr.APPS_TOP_SELLING_NEW_PAID = "apps_topselling_new_paid"
ctr.APPS_TOP_SELLING_NEW_FREE = "apps_topselling_new_free"
ctr.APPS_TRENDING = "apps_movers_shakers"

cat = space_constants()

# Application Root category
cat.APPLICATION = "APPLICATION"

# Application sub category
cat.ANDROID_WEAR = "ANDROID_WEAR"
cat.ART_AND_DESIGN = "ART_AND_DESIGN"
cat.AUTO_AND_VEHICLES = "AUTO_AND_VEHICLES"
cat.BEAUTY = "BEAUTY"
cat.BOOKS_AND_REFERENCE = "BOOKS_AND_REFERENCE"
cat.BUSINESS = "BUSINESS"
cat.COMICS = "COMICS"
cat.COMMUNICATION = "COMMUNICATION"
cat.DATING = "DATING"
cat.EDUCATION = "EDUCATION"
cat.ENTERTAINMENT = "ENTERTAINMENT"
cat.EVENTS = "EVENTS"
cat.FINANCE = "FINANCE"
cat.FOOD_AND_DRINK = "FOOD_AND_DRINK"
cat.HEALTH_AND_FITNESS = "HEALTH_AND_FITNESS"
cat.HOUSE_AND_HOME = "HOUSE_AND_HOME"
cat.LIBRARIES_AND_DEMO = "LIBRARIES_AND_DEMO"
cat.LIFESTYLE = "LIFESTYLE"
# cat.APP_WALLPAPER = "APP_WALLPAPER"
cat.MAPS_AND_NAVIGATION = "MAPS_AND_NAVIGATION"
# cat.MEDIA_AND_VIDEO = "MEDIA_AND_VIDEO"
cat.MEDICAL = "MEDICAL"
cat.MUSIC_AND_AUDIO = "MUSIC_AND_AUDIO"
cat.NEWS_AND_MAGAZINES = "NEWS_AND_MAGAZINES"
cat.PARENTING = "PARENTING"
cat.PERSONALIZATION = "PERSONALIZATION"
cat.PHOTOGRAPHY = "PHOTOGRAPHY"
cat.PRODUCTIVITY = "PRODUCTIVITY"
cat.SHOPPING = "SHOPPING"
cat.SOCIAL = "SOCIAL"
cat.SPORTS = "SPORTS"
cat.TOOLS = "TOOLS"
cat.TRANSPORTATION = "TRANSPORTATION"
cat.TRAVEL_AND_LOCAL = "TRAVEL_AND_LOCAL"
cat.VIDEO_PLAYERS = "VIDEO_PLAYERS"
cat.WEATHER = "WEATHER"
# cat.APP_WIDGETS = "APP_WIDGETS"

# Family(kids) root category
cat.FAMILY = "FAMILY"

# family sub category
cat.FAMILY_ACTION = "FAMILY_ACTION"
cat.FAMILY_BRAINGAMES = "FAMILY_BRAINGAMES"
cat.FAMILY_CREATE = "FAMILY_CREATE"
cat.FAMILY_EDUCATION = "FAMILY_EDUCATION"
cat.FAMILY_MUSICVIDEO = "FAMILY_MUSICVIDEO"
cat.FAMILY_PRETEND = "FAMILY_PRETEND"

# GAME root category
cat.GAME = "GAME"

# GAME sub category
cat.GAME_ACTION = "GAME_ACTION"
cat.GAME_ADVENTURE = "GAME_ADVENTURE"
cat.GAME_ARCADE = "GAME_ARCADE"
cat.GAME_BOARD = "GAME_BOARD"
cat.GAME_CARD = "GAME_CARD"
cat.GAME_CASINO = "GAME_CASINO"
cat.GAME_CASUAL = "GAME_CASUAL"
cat.GAME_EDUCATIONAL = "GAME_EDUCATIONAL"
cat.GAME_MUSIC = "GAME_MUSIC"
cat.GAME_PUZZLE = "GAME_PUZZLE"
cat.GAME_RACING = "GAME_RACING"
cat.GAME_ROLE_PLAYING = "GAME_ROLE_PLAYING"
cat.GAME_SIMULATION = "GAME_SIMULATION"
cat.GAME_SPORTS = "GAME_SPORTS"
cat.GAME_STRATEGY = "GAME_STRATEGY"
cat.GAME_TRIVIA = "GAME_TRIVIA"
cat.GAME_WORD = "GAME_WORD"